### ISSUE TITLE
App crash with isbn retrieving

### ISSUE THREAD

**Issue by SarahKurek** [UniRegensburg/unsere-app-fur-die-universitat-regensburg-bib-buddy#158]
App crashes in **ISBN search** if the author exists in different spellings, because then the format "last name, first name" is not necessarily true. Then the authorList has one element, which is **null**, what then leads to a crash because of missing error catching.

The test was done with the ISBN: **9783150012413**
Link to related the dataset: https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=nid=118577468 
or http://d-nb.info/gnd/118577468

Also if the book has **multiple authors**, only the first one is taken over and not all of them, but here I don't know if it's because there's a split between main and co-authors (ISBN 9780262038904).

**Comment by LuisMossburger** [comment]
Hey, thanks for the information!

1) The reason here is that "Marc Aurel" is not a regular "name" but an so-called "Eigenname". I would suggest either creating a new database field for that or, faster to implement, saving that to the "first name" and leaving "last name" empty. 

2) In other cases, all authors are correctly added to the new book item. In this case, librarians have actively decided to show "Eriksson, Maria" as most important and primary authors and others only as "contributors". So in that case, only taking her is expected behavior and I would suggest leaving it that way. What is your opinion? :)

**Comment by SarahKurek** [comment]
It's okay for me.
